### ISSUE TITLE
XYZ color picker confuses 0..1 and 0..100% range

### ISSUE THREAD

**Issue by svgeesus** [color-js/apps#2]
The [XYZ-d65 color picker](https://colorjs.io/apps/picker/xyz-d65) has 0..100 scale but gives black for [0,0,0] and an oog color close to white for [1,1,1]; it is not possible to pick any other colors due to the slider granularity.

![image](https://user-images.githubusercontent.com/2506926/176907422-450b07d9-2821-43ba-80ff-d9bcad958c69.png)

**Comment by svgeesus** [comment]
Confirming that the issue still exists, because [0..1] and [0..100] are being confused

**Comment by LeaVerou** [comment]
What should the range be for each XYZ space?

**Comment by svgeesus** [comment]
As I [said earlier](https://github.com/color-js/apps/issues/2#issuecomment-2134714494):

> Giving the relative XYZs a reference range of [0, 1] would also work.

**Comment by LeaVerou** [comment]
@DmitrySharabin could we integrate the [`<color-picker>`](https://elements.colorjs.io/src/color-picker/) component to use here so we don't maintain similar code in two places?

**Comment by DmitrySharabin** [comment]
> @DmitrySharabin could we integrate the [`<color-picker>`](https://elements.colorjs.io/src/color-picker/) component to use here so we don't maintain similar code in two places?

@LeaVerou, I integrated the `<color-picker>` component ([preview](https://deploy-preview-12--color-apps.netlify.app/picker/) and [corresponding PR](https://github.com/color-js/apps/pull/12)). Please take a look.

**Comment by LeaVerou** [comment]
Thanks @DmitrySharabin! Is this issue present in `<color-picker>` too? If not, we should close.

**Comment by DmitrySharabin** [comment]
> Is this issue present in `<color-picker>` too?

Unfortunately, it does. As @svgeesus mentioned, since `xyzd65` and `xyzd50` don't declare a range, they end up with `[0, 100]` ([here](https://github.com/color-js/elements/blob/ac6b3ab3c38ea0efb0239005a2b19da5ad3637a1/src/channel-slider/channel-slider.js#L176) and [here](https://github.com/color-js/elements/blob/ac6b3ab3c38ea0efb0239005a2b19da5ad3637a1/src/channel-slider/channel-slider.js#L233)). In `<color-picker>`, [we don't fall back to `[0, 100]`](https://github.com/color-js/elements/blob/ac6b3ab3c38ea0efb0239005a2b19da5ad3637a1/src/color-picker/color-picker.js#L192) (when calculating the default color) expecting that _all the color spaces declare ranges for their coords_ (that make `<color-picker>` throw for the mentioned color spaces).

So, to solve this issue, we should probably declare ranges for those spaces. As [Chris said](https://github.com/color-js/apps/issues/2#issuecomment-2134714494):

> Giving the relative XYZs a reference range of [0, 1] would also work.

**Comment by LeaVerou** [comment]
Yeah, let's do that.

**Comment by DmitrySharabin** [comment]
> Yeah, let's do that.

[Done](https://github.com/color-js/color.js/pull/620).

**Comment by DmitrySharabin** [comment]
Fixed in [a3e89582cfe9873e790a21b2f593b8bc4a7abcb5](https://github.com/color-js/color.js/commit/a3e89582cfe9873e790a21b2f593b8bc4a7abcb5)
